import type { Metadata } from 'next';
import CenteredLayout from '@/layouts/Centered';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <CenteredLayout>{children}</CenteredLayout>;
}
